### ISSUE TITLE
Edit on GitHub links broken

### ISSUE THREAD

**Issue by buildersbrewery** [evildmp/documentation-system#3]
Your "Edit on GitHub" links are broken, probably cause your string concatenation adds a redundant forward slash to the beginning of the second part.

**Comment by nbraud** [comment]
The second forward slash is not the only issue (removing it manually doesn't fix links)

**Comment by usethedata** [comment]
A link that works: `https://github.com/evildmp/documentation-system/blob/master/introduction.rst`

Your link: `https://github.com/evildmp/documentation-system//master/introduction`

**Comment by umarcor** [comment]
Since this theme is based on the one from ReadTheDocs, adding the following to your config file might fix it:

```py
html_theme_options = {
    'vcs_pageview_mode': 'blob',
}
```

Unfortunately, sources seem not to be available (#6), so I cannot confirm.

**Comment by evildmp** [comment]
Fixed.
