### ISSUE TITLE
Sources of the theme

### ISSUE THREAD

**Issue by umarcor** [evildmp/documentation-system#6]
I'd like to both use theme https://pypi.org/project/divio-docs-theme/ and to contribute some enhancements. However, it seems that https://github.com/divio/divio-docs-theme/ no longer exists. Are sources of the theme available in any other repo?

**Comment by jest** [comment]
It's probably at https://github.com/divio/docs-theme/

**Comment by evildmp** [comment]
Now using a different theme at https://diataxis.fr.
